"""Ranking parity: the Python ranker must order hits exactly like the JS one.

Not a style preference — a correctness requirement, and there are now TWO of
them.

**One box, two rankers.** The in-folder search answers from the index (ranked
here, in Python) for every folder a scan can cover, and from a live streamed
walk (ranked in the browser by listing/search.ts, the only thing that CAN rank
a stream) for the folders no scan will ever cover — a remote mount, a package,
a folder the ignore list excludes. That is a narrower set than it used to be,
but it is not empty and it never will be: a user searching a mounted bucket and
the same user searching a local project must get the same ordering, or the box
appears to change its mind about relevance depending on where the folder lives.

**One row, two languages.** The sharper reason, and it applies to every ranked
answer rather than to a shrinking minority of folders: the server RANKS and the
browser HIGHLIGHTS. `/api/index/rank` deliberately does not return match
positions — the client re-runs `fuzzyMatch` over the rows it got back
(listing/ranked-hits) — so a divergence between the two implementations puts
the highlight on the wrong characters of a hit the other language ranked first,
or leaves a top hit with no highlight at all.

So the JS ranker is the authority and this asserts against a fixture generated
from it (tests/fixtures/rank-parity.json, regenerated by
`bun scripts/gen-rank-fixture.ts`). The mirror-image test lives in
frontend/src/apps/explorer/listing/rank-parity.test.ts, so a change to the JS
ordering fails there and a Python drift fails here.
"""
import json
from pathlib import Path

import pytest

from fused_render.index.cancel import Cancelled
from fused_render.index.rank import fuzzy_match, max_span, rank_entries

FIXTURE = json.loads(
    (Path(__file__).resolve().parent / "fixtures" / "rank-parity.json")
    .read_text(encoding="utf-8"))


@pytest.mark.parametrize("query", FIXTURE["queries"])
def test_python_ranking_matches_the_js_ranker(query):
    ranked = rank_entries(query, FIXTURE["entries"])
    assert [h["rel"] for h in ranked] == FIXTURE["expected"][query]


def test_positions_mark_the_matched_characters():
    """`positions` drives the highlight, so it travels with the hit."""
    [hit] = [h for h in rank_entries("readme", FIXTURE["entries"])
             if h["rel"] == "README.md"]
    assert ["README.md"[i] for i in hit["positions"]] == list("README")


def test_an_empty_query_ranks_nothing():
    assert rank_entries("", FIXTURE["entries"]) == []
    assert rank_entries("   ", FIXTURE["entries"]) == []


def test_hits_carry_the_entry_fields_through():
    """The endpoint returns these rows verbatim, so the ranker must not eat
    the fields the client renders."""
    [hit] = [h for h in rank_entries("environment.yml", FIXTURE["entries"])
             if h["rel"] == "environment.yml"]
    assert hit["is_dir"] is False
    assert hit["size"] == 10 and hit["mtime"] == 1
    assert hit["score"] > 100  # exact-name bonus applied
    assert hit["tier"] == 1 and hit["depth"] == 1


def test_the_substring_branch_beats_a_tighter_looking_fuzzy_one():
    """longestRun = len(query) is the invariant rank_compare leans on."""
    m = fuzzy_match("cfg", "mycfgfile.txt")
    assert m is not None and m["longest_run"] == 3


def test_the_span_bound_refuses_a_whole_path_smear():
    assert max_span(3) == 17
    # "zmp" over the prose title spans 20 > 17, so it is refused outright.
    assert fuzzy_match("zmp", "Zarr v3 multiscale pyramid budget notes.md") is None


def test_hidden_entries_need_a_dot_leading_query_segment():
    assert ".env" not in [h["rel"] for h in rank_entries("env", FIXTURE["entries"])]
    assert ".env" in [h["rel"] for h in rank_entries(".env", FIXTURE["entries"])]


def _rels(query, entries):
    return [h["rel"] for h in rank_entries(query, [{"rel": r} for r in entries])]


def test_a_shallow_name_match_beats_a_deep_ancestor_only_match():
    """A vague query where the deep candidate's own name doesn't match at all
    (tier 3) must not beat a shallow candidate whose name matches, even
    fuzzily (tier 2) — this is `tier` doing its job, not the depth penalty,
    but it's the floor the penalty is layered on top of."""
    deep = "a/b/c/d/e/f/g/h/notes.txt"
    shallow = "cfg-manager.txt"
    assert _rels("cfg", [deep, shallow])[0] == shallow


def test_a_deep_scattered_ancestor_only_match_no_longer_wins_on_score_alone():
    """The reported bug: a vague query where NOBODY's own name matches (tier 3
    for everyone), so the sort falls through to raw score — where a long
    ancestor chain simply offers more +5 segment-start bonuses than a short
    one, independent of relevance. Same tier, same longest_run (a scattered
    subsequence for both), so this is decided by score/depth alone — exactly
    the case DEPTH_PENALTY exists for. Mirrors search.test.ts's identical
    case, which is where this pair was found."""
    deep = ("src/chat/ChatInterface/components/MessageList/components/"
            "MessageScrollbackRail/index.ts")
    shallow = "cache-config/comp/widget.ts"
    assert _rels("cccm", [deep, shallow])[0] == shallow


def test_a_deep_exact_name_match_still_wins_over_a_shallow_fuzzy_one():
    """The penalty must not swamp the +100 exact-name bonus."""
    deep = "a/b/c/d/e/f/g/h/exact-match.txt"
    shallow = "s/fuzzy-only.txt"
    assert _rels("exact-match.txt", [shallow, deep])[0] == deep


# -- cancellation: `token` hears the scoring loop, not just the boundaries ---
#
# `search_ranked` (query.py) already checked its token immediately BEFORE
# calling `rank_entries`; the gap this closes is INSIDE the loop, which is
# pure Python holding the GIL — no duckdb call is in flight for
# `con.interrupt()` to reach once scoring starts. `Cancelled` is Python-only
# plumbing and must never touch scoring/ordering (rank-parity.json stays the
# authority), so these tests only assert on *whether* and *when* it raises,
# never on the ranking itself.

class _CountingToken:
    """A fake CancelToken: raises `Cancelled` once `check()` has been called
    more than `raise_after` times, so a test can pin exactly which check call
    trips it."""

    def __init__(self, raise_after):
        self.raise_after = raise_after
        self.calls = 0

    def check(self):
        self.calls += 1
        if self.calls > self.raise_after:
            raise Cancelled()


def test_rank_entries_ignores_a_token_that_never_cancels():
    token = _CountingToken(raise_after=10_000)
    entries = [{"rel": f"dir/file{i}.txt"} for i in range(600)]
    ranked = rank_entries("file", entries, token=token)
    assert len(ranked) == 600
    # Checked periodically (every 256) AND once before the final sort — for
    # 600 entries that's checks at i=0, 256, 512, plus the pre-sort one.
    assert token.calls == 4


def test_rank_entries_raises_cancelled_mid_loop_not_only_at_the_end():
    """The check the search box actually needs: entries far past 256 are
    never scored once the token trips, proving this is a genuine mid-loop
    stop and not equivalent to a single check before/after the whole pass."""
    token = _CountingToken(raise_after=1)  # survives the i=0 check, not i=256
    entries = [{"rel": f"dir/file{i}.txt"} for i in range(600)]
    with pytest.raises(Cancelled):
        rank_entries("file", entries, token=token)
    assert token.calls == 2  # i=0, then i=256 — no third (pre-sort) check


def test_rank_entries_cancelled_before_the_first_entry_scores_nothing():
    token = _CountingToken(raise_after=0)
    entries = [{"rel": "file.txt"}]
    with pytest.raises(Cancelled):
        rank_entries("file", entries, token=token)


def test_rank_entries_with_no_token_behaves_exactly_as_before():
    """`token=None` is the default every EXISTING caller still uses — this
    pins that adding the parameter changed nothing for them."""
    entries = [{"rel": f"dir/file{i}.txt"} for i in range(600)]
    assert rank_entries("file", entries) == rank_entries("file", entries, token=None)
