"""Ranking parity: the Python ranker must order hits exactly like the JS one.

Not a style preference — a correctness requirement the in-folder search box
forces. That box answers from either source depending on coverage: the index
leg (ranked here, in Python) or a live streamed walk of a folder the index
cannot answer (ranked in the browser by listing/search.ts, which is the only
thing that CAN rank a stream). A folder this app renamed an hour ago is pinned
to the walk for the session (lib/index-freshness), so the same query in the
same box can be answered by either ranker — and if they disagree, the result
order changes for reasons no user can see.

So the JS ranker is the authority and this asserts against a fixture generated
from it (tests/fixtures/rank-parity.json, regenerated by
`bun scripts/gen-rank-fixture.ts`). The mirror-image test lives in
frontend/src/apps/explorer/listing/rank-parity.test.ts, so a change to the JS
ordering fails there and a Python drift fails here.
"""
import json
from pathlib import Path

import pytest

from fused_render.index.rank import fuzzy_match, max_span, rank_entries

FIXTURE = json.loads(
    (Path(__file__).resolve().parent / "fixtures" / "rank-parity.json")
    .read_text(encoding="utf-8"))


@pytest.mark.parametrize("query", FIXTURE["queries"])
def test_python_ranking_matches_the_js_ranker(query):
    ranked = rank_entries(query, FIXTURE["entries"])
    assert [h["rel"] for h in ranked] == FIXTURE["expected"][query]


def test_positions_mark_the_matched_characters():
    """`positions` drives the highlight, so it travels with the hit."""
    [hit] = [h for h in rank_entries("readme", FIXTURE["entries"])
             if h["rel"] == "README.md"]
    assert ["README.md"[i] for i in hit["positions"]] == list("README")


def test_an_empty_query_ranks_nothing():
    assert rank_entries("", FIXTURE["entries"]) == []
    assert rank_entries("   ", FIXTURE["entries"]) == []


def test_hits_carry_the_entry_fields_through():
    """The endpoint returns these rows verbatim, so the ranker must not eat
    the fields the client renders."""
    [hit] = [h for h in rank_entries("environment.yml", FIXTURE["entries"])
             if h["rel"] == "environment.yml"]
    assert hit["is_dir"] is False
    assert hit["size"] == 10 and hit["mtime"] == 1
    assert hit["score"] > 100  # exact-name bonus applied
    assert hit["tier"] == 1 and hit["depth"] == 1


def test_the_substring_branch_beats_a_tighter_looking_fuzzy_one():
    """longestRun = len(query) is the invariant rank_compare leans on."""
    m = fuzzy_match("cfg", "mycfgfile.txt")
    assert m is not None and m["longest_run"] == 3


def test_the_span_bound_refuses_a_whole_path_smear():
    assert max_span(3) == 17
    # "zmp" over the prose title spans 20 > 17, so it is refused outright.
    assert fuzzy_match("zmp", "Zarr v3 multiscale pyramid budget notes.md") is None


def test_hidden_entries_need_a_dot_leading_query_segment():
    assert ".env" not in [h["rel"] for h in rank_entries("env", FIXTURE["entries"])]
    assert ".env" in [h["rel"] for h in rank_entries(".env", FIXTURE["entries"])]
