import sys, os; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from bot import *
import subprocess, statistics

TA = "data:text/html,<textarea id=t autofocus style='width:500px;height:200px'></textarea>"

class Env:
    """bot Chrome (headless) + driver Chrome (headless, plays the HUMAN's browser) + http server for liveview.html"""
    def __init__(self, tag="B"):
        self.hport = free_port()
        self.http = subprocess.Popen([sys.executable, "-m", "http.server", str(self.hport), "--bind", "127.0.0.1"], cwd=os.path.dirname(os.path.abspath(__file__)),
                                     stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, start_new_session=True)
        self.bot = launch(f"{S}/profiles/{tag}-bot", headless=True, extra=[f"--remote-allow-origins=http://127.0.0.1:{self.hport}"])
        self.drv = launch(f"{S}/profiles/{tag}-drv", headless=True)
        self.mode = "bot"
        self.page = pages(self.bot["port"])[0]
        self.tid = self.page["id"]
        self.ws = WS(self.page["webSocketDebuggerUrl"]); self.ws.call("Page.enable")
        self.dws = WS(pages(self.drv["port"])[0]["webSocketDebuggerUrl"]); self.dws.call("Page.enable")
        self.lv_open = False

    def goto(self, url, ws=None):
        ws = ws or self.ws
        ws.call("Page.navigate", url=url); time.sleep(.7)

    def open_liveview(self, mac=True, tid=None):
        tid = tid or self.tid
        wsu = f"ws://127.0.0.1:{self.bot['port']}/devtools/page/{tid}"
        self.dws.call("Page.navigate", url=f"http://127.0.0.1:{self.hport}/liveview.html?mac={1 if mac else 0}&ws={wsu}")
        for _ in range(60):
            if self.dws.evaluate("window.__open===true && __stats.frames>0"): break
            time.sleep(.1)
        else: raise RuntimeError("liveview never got frames")
        # human clicks canvas to focus capture textarea (real mouse path through the forwarder too, once enabled)
        self.lv_open = True

    # --- take-over / hand-back are a FLAG, nothing else
    def take_over(self):
        t = time.perf_counter(); self.mode = "human"; self.dws.evaluate("window.__input=true; document.getElementById('c').className='on'; document.getElementById('cap').focus(); 1"); return time.perf_counter() - t
    def hand_back(self):
        t = time.perf_counter(); self.mode = "bot"; self.dws.evaluate("window.__input=false; document.getElementById('c').className=''; 1"); return time.perf_counter() - t

    # --- bot side ops (refuse while human drives)
    def bot_type(self, s):
        assert self.mode == "bot", "bot must not drive during take-over"; type_str(self.ws, s)

    # --- the HUMAN: real KeyboardEvents generated by the driver Chrome into the live-view page
    def h_key(self, key, code=None, **mods):
        ws = self.dws
        c = code
        if c is None:
            cc = CHAR2CODE.get(key); c = cc[0] if cc else ""
            if cc and cc[1]: mods["shift"] = True
        if mods.get("shift") and len(key) == 1 or (mods.get("shift") and key not in ("Shift",)):
            pass
        if mods.get("shift"): self._mod("Shift", "ShiftLeft", 16, 8, True)
        for m, k, cd, vk, bit in (("ctrl","Control","ControlLeft",17,2),("alt","Alt","AltLeft",18,1),("meta","Meta","MetaLeft",91,4)):
            if mods.get(m): self._mod(k, cd, vk, bit, True)
        kp = keyparams(key, c, **{k: v for k, v in mods.items()}, mac=True)
        if "insert" in kp:  # layout produces a char the US table lacks -> a real browser still emits keydown with key=char
            ws.call("Input.dispatchKeyEvent", type="keyDown", key=key, code=c or "KeyE", text=key, unmodifiedText=key, windowsVirtualKeyCode=0)
            ws.call("Input.dispatchKeyEvent", type="keyUp", key=key, code=c or "KeyE")
        else:
            d = dict(kp["down"]); d.pop("commands", None)  # human's browser doesn't send commands; the forwarder derives them
            if mods.get("meta") or mods.get("ctrl"): d["type"] = "rawKeyDown"; d.pop("text", None); d.pop("unmodifiedText", None)
            ws.call("Input.dispatchKeyEvent", **d); ws.call("Input.dispatchKeyEvent", **kp["up"])
        for m, k, cd, vk, bit in (("meta","Meta","MetaLeft",91,4),("alt","Alt","AltLeft",18,1),("ctrl","Control","ControlLeft",17,2)):
            if mods.get(m): self._mod(k, cd, vk, bit, False)
        if mods.get("shift"): self._mod("Shift", "ShiftLeft", 16, 8, False)

    def _mod(self, key, code, vk, bit, down):
        self.dws.call("Input.dispatchKeyEvent", type="rawKeyDown" if down else "keyUp", key=key, code=code, windowsVirtualKeyCode=vk, modifiers=bit if down else 0)

    def h_type(self, s):
        for ch in s:
            if ch == "\n": self.h_key("Enter")
            else: self.h_key(ch)

    def h_click_canvas(self, fx, fy):
        r = self.dws.evaluate("(()=>{const r=document.getElementById('c').getBoundingClientRect();return [r.left,r.top,r.width,r.height]})()")
        x, y = r[0] + r[2] * fx, r[1] + r[3] * fy
        for t in ("mousePressed", "mouseReleased"):
            self.dws.call("Input.dispatchMouseEvent", type=t, x=x, y=y, button="left", clickCount=1, buttons=1 if t == "mousePressed" else 0)

    def h_shot(self, path):
        d = self.dws.call("Page.captureScreenshot", format="png")["data"]
        open(path, "wb").write(base64.b64decode(d))

    def close(self):
        for s in (self.bot, self.drv): kill(s)
        try: os.killpg(self.http.pid, signal.SIGKILL)
        except Exception: pass
