// The JS half of the cross-language ranking contract.
//
// Home search now filters AND ranks on the server (fused_render/index/rank.py),
// while the in-folder search over a live streamed walk is still ranked here —
// this module is the only thing that CAN rank a stream. Two rankers answer the
// same box, so they must agree, and tests/fixtures/rank-parity.json is the
// agreement, generated from THIS ranker (`bun scripts/gen-rank-fixture.ts`).
//
// This test's job is to fail loudly when the JS ordering changes: an
// intentional change means regenerating the fixture AND updating rank.py, and
// silently letting the two drift is the bug it exists to prevent. Its mirror
// is tests/test_index_rank.py.
import { readFileSync } from "node:fs";
import { expect, test } from "bun:test";
import type { WalkEntry } from "@platform/lib/api";
import { queryWantsHidden, rankCompare, scoreEntries } from "@apps/explorer/listing/search";

// Read, not imported: the fixture lives in the repo's tests/ tree (it is shared
// with pytest and generated by a repo-level script), and the import-boundary
// check rightly refuses an app reaching outside src/ with an import statement.
const fixture = JSON.parse(
  readFileSync(new URL("../../../../../tests/fixtures/rank-parity.json", import.meta.url), "utf8"),
) as { entries: WalkEntry[]; queries: string[]; expected: Record<string, string[]> };

const entries = fixture.entries;

test("the fixture covers the queries it says it does", () => {
  expect(fixture.queries.length).toBeGreaterThan(0);
  expect(Object.keys(fixture.expected).sort()).toEqual([...fixture.queries].sort());
});

for (const q of fixture.queries) {
  test(`the JS ranker still produces the fixture order for ${JSON.stringify(q)}`, () => {
    const hits = scoreEntries(q, entries, 0, queryWantsHidden(q));
    hits.sort(rankCompare);
    expect(hits.map((h) => h.entry.rel)).toEqual(
      fixture.expected[q],
    );
  });
}
