"""py2app build spec for FusedRender.app (SPEC D33-D35).

Invoked by build_dmg.sh as:
    python scripts/setup_py2app.py py2app --dist-dir <dir>

Not a normal package build — `python_requires`/deps etc. are irrelevant here;
this only describes how py2app should assemble the .app bundle. The actual
fused-render + [bundled,app] install happens into the build venv beforehand
(see build_dmg.sh); py2app then copies what's importable from that venv.

`packages` (below) forces WHOLE-DIRECTORY copies instead of py2app's default
"trace imports statically, freeze into a zip" behavior. Two independent
reasons every one of these needs it:
  1. Binary/data-bearing packages (numpy, pandas, pyarrow, scipy, geopandas,
     matplotlib's mpl-data, ...) ship .so/.dylib files and non-Python data
     that a zipped archive can't hold anyway.
  2. fused-render's own execution model: user scripts run through openfused's
     local backend (fused_render/engine.py) in CHILD PROCESSES inside venvs
     created at runtime, not via a static `import` anywhere in fused_render's
     own source. py2app's modulegraph only sees imports it can trace from
     app_entry.py's call graph, so it is structurally blind to whatever a
     user's script imports at runtime (pandas, pyarrow, PIL, ...). Every
     package promised by the `[bundled]` extra (SPEC DM-2) must therefore be
     forced in explicitly — there is no static import for modulegraph to find
     in the first place.
"""
import os
import re
import sys

from setuptools import setup

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(SCRIPT_DIR)

with open(os.path.join(REPO_ROOT, "pyproject.toml")) as f:
    _pyproject = f.read()
VERSION = re.search(r'(?m)^version\s*=\s*"([^"]+)"', _pyproject).group(1)

# Generated by build_dmg.sh before invoking py2app (see its icon-generation
# step) — not committed, lives under build/.
ICONFILE = os.environ.get("FUSED_RENDER_ICNS")
if not ICONFILE or not os.path.isfile(ICONFILE):
    sys.exit(f"FUSED_RENDER_ICNS must point at an existing .icns file (got: {ICONFILE!r})")

# Built by build_dmg.sh (pip download into build/wheels) before invoking
# py2app — the offline wheelhouse for openfused's PEP 723 venv installs.
# Shipped via `resources` below so it lands at Contents/Resources/wheels;
# fused_render/app.py points PIP_FIND_LINKS/UV_FIND_LINKS at it at startup.
WHEELS_DIR = os.environ.get("FUSED_RENDER_WHEELS")
if not WHEELS_DIR or not os.path.isdir(WHEELS_DIR):
    sys.exit(f"FUSED_RENDER_WHEELS must point at an existing wheels directory (got: {WHEELS_DIR!r})")

# Built by build_dmg.sh (§2c): the bundled uv binary, shipped to
# Contents/Resources/appbin. openfused's PEP 723 venv installs must go through
# uv — under the stub's inherited PYTHONHOME, `<venv-python> -m pip install`
# poisons the venv cache (installs into the bundle, leaves the venv empty) —
# and Finder-launched apps have no uv on their minimal PATH, so
# fused_render/app.py prepends this directory at startup.
BIN_DIR = os.environ.get("FUSED_RENDER_BIN")
if not BIN_DIR or not os.path.isfile(os.path.join(BIN_DIR, "uv")):
    sys.exit(f"FUSED_RENDER_BIN must point at a directory containing uv (got: {BIN_DIR!r})")

# Built by build_dmg.sh (§2d): python-build-standalone, shipped to
# Contents/Resources/python-standalone — the base interpreter for user-script
# venvs (D67). The frozen py2app interpreter can't reliably serve as a venv
# base (PYTHONHOME-stripped children must self-locate its stdlib);
# fused_render/engine.py auto-detects this directory and passes it to the
# openfused backend as python_executable. Directory name matters: engine.py
# looks for sys.prefix + "/python-standalone/bin/python3".
PYSTANDALONE_DIR = os.environ.get("FUSED_RENDER_PYSTANDALONE")
if not PYSTANDALONE_DIR or not os.path.isfile(os.path.join(PYSTANDALONE_DIR, "bin", "python3")):
    sys.exit(
        "FUSED_RENDER_PYSTANDALONE must point at a directory containing bin/python3 "
        f"(got: {PYSTANDALONE_DIR!r})"
    )

APP = [os.path.join(SCRIPT_DIR, "app_entry.py")]

# Extensions the built-in template registry (server.py TEMPLATES) previews.
# Kept in sync by hand — see ARCHITECTURE.md §7 for the source of truth.
_PREVIEWABLE_EXTENSIONS = [
    "html", "htm", "csv", "tsv", "json", "geojson", "md", "txt", "log",
    "yaml", "yml", "toml", "py", "js", "ts", "sh", "css",
    "png", "jpg", "jpeg", "gif", "webp", "svg", "xlsx", "pdf",
    "mp4", "mov", "m4v", "webm", "mp3", "wav", "m4a", "ogg", "flac",
]

DOCUMENT_TYPES = [
    {
        "CFBundleTypeName": "Apache Parquet data",
        "CFBundleTypeRole": "Viewer",
        "LSHandlerRank": "Default",  # no other app owns .parquet
        "CFBundleTypeExtensions": ["parquet"],
    },
    {
        "CFBundleTypeName": "FusedRender previewable file",
        "CFBundleTypeRole": "Viewer",
        "LSHandlerRank": "Alternate",  # never steals the user's default app
        "CFBundleTypeExtensions": _PREVIEWABLE_EXTENSIONS,
    },
]

OPTIONS = {
    "argv_emulation": False,  # rumps/app.py owns AppKit file-open handling directly (application:openFiles:)
    "iconfile": ICONFILE,
    "packages": [
        "fused_render",
        # openfused local backend ("fused" dist): fused_render/engine.py
        # imports it lazily (inside get_backend), and it reads its handler
        # files off disk via Path(__file__) — both patterns a zipped copy
        # breaks, so whole-dir copy.
        "fused",
        # stdlib venv machinery: openfused creates per-script venvs by
        # re-invoking `sys.executable -m venv` in a SUBPROCESS — no static
        # import for modulegraph to trace — and ensurepip's bundled pip
        # wheel is data a zip can't serve.
        "venv", "ensurepip",
        # Engine (fused dist) hard dependencies with native/binary payloads —
        # NOT the old [bundled] user stack (dropped from the bundle: user
        # scripts import from openfused venvs fed by the wheelhouse, D56/D58).
        # These ship only because the fused dist requires them.
        "numpy", "pandas", "dateutil", "six",
        "pyarrow",
        # _duckdb deliberately NOT here: it's a bare top-level C extension
        # (site-packages/_duckdb.cpython-312-darwin.so), not a package.
        # Forcing it via `packages` makes py2app copy the Mach-O binary to
        # lib/python3.12/_duckdb.py, which shadows the real
        # lib-dynload/_duckdb.so and breaks `import duckdb` with
        # "SyntaxError: source code string cannot contain null bytes".
        # It goes in `includes` below instead.
        "duckdb",
        "requests", "urllib3", "certifi", "charset_normalizer", "idna",
        # web server stack: forced full-copy too, since uvicorn/pydantic-core
        # do dynamic/compiled imports modulegraph can't always follow.
        "fastapi", "starlette", "uvicorn", "h11", "click", "anyio",
        "pydantic", "pydantic_core", "typing_extensions", "typing_inspection",
        "annotated_types", "annotated_doc", "packaging",
        # menu-bar app shell. PyObjCTools deliberately excluded: same
        # namespace-package (no __init__.py) limitation as mpl_toolkits
        # above. rumps's own static `import` of what it needs from
        # PyObjCTools (e.g. AppHelper) is still picked up normally by
        # modulegraph's regular import tracing - only forcing the whole
        # package via `packages` breaks on its bootstrap lookup.
        "rumps", "objc", "AppKit", "Foundation", "Cocoa", "CoreFoundation",
    ],
    # Single modules (incl. bare C extensions) that modulegraph can't be
    # trusted to find on its own — same runtime-import blindness as
    # `packages` above, but `includes` handles non-package modules correctly
    # (extension -> lib-dynload/*.so, never a bogus .py copy).
    "includes": ["_duckdb"],
    # PIL is present in the BUILD venv (icon generation is a build step) but
    # is not app code — keep modulegraph from dragging it into the bundle.
    "excludes": ["PIL"],
    # Copied verbatim into Contents/Resources/: the wheelhouse dir (named
    # "wheels") lands at Contents/Resources/wheels, the uv dir (named
    # "appbin") at Contents/Resources/appbin, the standalone interpreter
    # (named "python-standalone") at Contents/Resources/python-standalone.
    "resources": [WHEELS_DIR, BIN_DIR, PYSTANDALONE_DIR],
    "plist": {
        "CFBundleIdentifier": "io.fused.render",
        "CFBundleName": "FusedRender",
        "CFBundleDisplayName": "FusedRender",
        "CFBundleShortVersionString": VERSION,
        "CFBundleVersion": VERSION,
        "LSMinimumSystemVersion": "11.0",
        "NSHighResolutionCapable": True,
        # No LSUIElement (D34): regular app, Dock icon + menu bar item both.
        # Finder "Open with FusedRender" (SPEC DM-8):
        "CFBundleDocumentTypes": DOCUMENT_TYPES,
    },
}

setup(
    app=APP,
    name="FusedRender",
    version=VERSION,
    options={"py2app": OPTIONS},
    # py2app is already installed into the build venv directly (see
    # build_dmg.sh) - not declared as setup_requires: modern setuptools
    # dropped the old easy_install-based fetch-at-setup-time mechanism
    # entirely ("install_requires is no longer supported" if you try).
)
