"""py2app build spec for FusedRender.app (SPEC D33-D35).

Invoked by build_dmg.sh as:
    python scripts/setup_py2app.py py2app --dist-dir <dir>

Not a normal package build — `python_requires`/deps etc. are irrelevant here;
this only describes how py2app should assemble the .app bundle. The actual
fused-render + [bundled,app] install happens into the build venv beforehand
(see build_dmg.sh); py2app then copies what's importable from that venv.

`packages` (below) forces WHOLE-DIRECTORY copies instead of py2app's default
"trace imports statically, freeze into a zip" behavior. Two independent
reasons every one of these needs it:
  1. Binary/data-bearing packages (numpy, pandas, pyarrow, scipy, geopandas,
     matplotlib's mpl-data, ...) ship .so/.dylib files and non-Python data
     that a zipped archive can't hold anyway.
  2. fused-render's own executor model: `runPython` loads arbitrary user .py
     files via importlib in a CHILD PROCESS (_child.py), not via a static
     `import` anywhere in fused_render's own source. py2app's modulegraph
     only sees imports it can trace from app_entry.py's call graph, so it
     is structurally blind to whatever a user's script imports at runtime
     (pandas, pyarrow, PIL, ...). Every package promised by the `[bundled]`
     extra (SPEC DM-2) must therefore be forced in explicitly — there is no
     static import for modulegraph to find in the first place.
"""
import os
import re
import sys

from setuptools import setup

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(SCRIPT_DIR)

with open(os.path.join(REPO_ROOT, "pyproject.toml")) as f:
    _pyproject = f.read()
VERSION = re.search(r'(?m)^version\s*=\s*"([^"]+)"', _pyproject).group(1)

# Generated by build_dmg.sh before invoking py2app (see its icon-generation
# step) — not committed, lives under build/.
ICONFILE = os.environ.get("FUSED_RENDER_ICNS")
if not ICONFILE or not os.path.isfile(ICONFILE):
    sys.exit(f"FUSED_RENDER_ICNS must point at an existing .icns file (got: {ICONFILE!r})")

APP = [os.path.join(SCRIPT_DIR, "app_entry.py")]

# Extensions the built-in template registry (server.py TEMPLATES) previews,
# kept in sync by hand (see ARCHITECTURE.md §7), plus geo/sci extras with no
# built-in key — users can bind those via the runtime template registry, and
# extra Finder associations are harmless at Alternate rank.
_PREVIEWABLE_EXTENSIONS = [
    "html", "htm", "csv", "tsv", "json", "geojson", "md", "txt", "log",
    "yaml", "yml", "toml", "py", "js", "ts", "sh", "css",
    "png", "jpg", "jpeg", "gif", "webp", "svg", "xlsx", "pdf",
    "mp4", "mov", "m4v", "webm", "mp3", "wav", "m4a", "ogg", "flac",
    "tif", "tiff", "geotiff",  # GeoTIFF rasters (server.py "geotiff" template)
    "nc", "nc4", "cdf",  # NetCDF (server.py "netcdf" template)
    # geo/sci formats with no built-in template key — bindable via the
    # runtime template registry:
    "gpkg", "shp", "fgb", "kml", "kmz", "gpx", "las", "laz",
    "pmtiles", "mbtiles", "zarr", "h5", "grib2", "jp2",
]

DOCUMENT_TYPES = [
    {
        "CFBundleTypeName": "Apache Parquet data",
        "CFBundleTypeRole": "Viewer",
        "LSHandlerRank": "Default",  # no other app owns .parquet
        "CFBundleTypeExtensions": ["parquet"],
    },
    {
        "CFBundleTypeName": "FusedRender previewable file",
        "CFBundleTypeRole": "Viewer",
        "LSHandlerRank": "Alternate",  # never steals the user's default app
        "CFBundleTypeExtensions": _PREVIEWABLE_EXTENSIONS,
    },
]

OPTIONS = {
    "argv_emulation": False,  # rumps/app.py owns AppKit file-open handling directly (application:openFiles:)
    "iconfile": ICONFILE,
    "packages": [
        "fused_render",
        # [bundled] extra (SPEC DM-2) + its native transitive deps, as
        # actually resolved in the build venv (see build_dmg.sh comments).
        "numpy", "pandas", "dateutil", "six",
        "pyarrow",
        # _duckdb deliberately NOT here: it's a bare top-level C extension
        # (site-packages/_duckdb.cpython-312-darwin.so), not a package.
        # Forcing it via `packages` makes py2app copy the Mach-O binary to
        # lib/python3.12/_duckdb.py, which shadows the real
        # lib-dynload/_duckdb.so and breaks `import duckdb` with
        # "SyntaxError: source code string cannot contain null bytes".
        # It goes in `includes` below instead.
        "duckdb", "adbc_driver_duckdb",
        "polars", "_polars_runtime_32",
        # mpl_toolkits deliberately excluded: it's a PEP 420 namespace
        # package (no __init__.py), and py2app's package-bootstrap lookup
        # (imp.find_module, pre-namespace-package semantics) can't resolve
        # it when forced via `packages`. matplotlib's core plotting (Agg,
        # pyplot, figures) works fine without it; only mpl_toolkits-specific
        # features (3D axes, axes_grid1, ...) are unavailable to user scripts.
        "matplotlib", "contourpy", "cycler", "fontTools", "kiwisolver", "pyparsing",
        "scipy",
        "PIL",
        "openpyxl", "et_xmlfile",
        "shapely",
        "geopandas", "pyogrio", "pyproj",
        "requests", "urllib3", "certifi", "charset_normalizer", "idna",
        # web server stack: forced full-copy too, since uvicorn/pydantic-core
        # do dynamic/compiled imports modulegraph can't always follow.
        "fastapi", "starlette", "uvicorn", "h11", "click", "anyio",
        "pydantic", "pydantic_core", "typing_extensions", "typing_inspection",
        "annotated_types", "annotated_doc", "packaging",
        # menu-bar app shell. PyObjCTools deliberately excluded: same
        # namespace-package (no __init__.py) limitation as mpl_toolkits
        # above. rumps's own static `import` of what it needs from
        # PyObjCTools (e.g. AppHelper) is still picked up normally by
        # modulegraph's regular import tracing - only forcing the whole
        # package via `packages` breaks on its bootstrap lookup.
        "rumps", "objc", "AppKit", "Foundation", "Cocoa", "CoreFoundation",
        # The deploy CLI (SPEC §19 DP-3): the [fused] extra build_dmg.sh
        # installs, run in-bundle via fused_render/_fused_cli.py. `fused`
        # itself is forced whole (pluggy entry-point plugins + pervasive
        # in-function imports + non-.py package data), plus the deps that
        # carry data dirs or dynamic loading a traced-module copy would
        # drop: botocore's JSON service models (boto3), anthropic's
        # tokenizer data, keyring's entry-point backends, cryptography's
        # cffi bindings, pluggy's registry. The rest of fused's dep tree is
        # pure-python with ordinary imports — modulegraph traces it. The
        # gate for anything missed here is build_dmg.sh §4c's bundled-CLI
        # smoke test (real verbs through the shim). `ty` is deliberately
        # NOT shipped (a Rust binary console script py2app can't carry);
        # fused's verify scanner detects its absence and skips with a
        # warning finding.
        "fused",
        "boto3", "botocore", "s3transfer", "jmespath",
        "cryptography", "keyring",
        "anthropic", "mcp", "httpx", "httpcore",
        "pluggy", "tomlkit", "jwt", "yaml", "loguru",
        "aiohttp", "yarl", "multidict", "frozenlist",
        "fsspec", "tabulate", "tqdm", "rtoml",
    ],
    # Single modules (incl. bare C extensions) that modulegraph can't be
    # trusted to find on its own — same runtime-import blindness as
    # `packages` above, but `includes` handles non-package modules correctly
    # (extension -> lib-dynload/*.so, never a bogus .py copy).
    # _cffi_backend: cryptography's cffi backend, the same bare-top-level-
    # C-extension shape as _duckdb.
    "includes": ["_duckdb", "_cffi_backend"],
    "plist": {
        "CFBundleIdentifier": "io.fused.render",
        "CFBundleName": "FusedRender",
        "CFBundleDisplayName": "FusedRender",
        "CFBundleShortVersionString": VERSION,
        "CFBundleVersion": VERSION,
        "LSMinimumSystemVersion": "11.0",
        "NSHighResolutionCapable": True,
        # No LSUIElement (D34): regular app, Dock icon + menu bar item both.
        # Finder "Open with FusedRender" (SPEC DM-8):
        "CFBundleDocumentTypes": DOCUMENT_TYPES,
        # macOS shows these strings in the TCC permission prompt when the app
        # first reads a file under a protected folder (the app browses the
        # whole filesystem by design, D2). Purpose strings don't change WHEN
        # the prompt appears — the D72 in-process-reader split + Developer ID
        # signing (D73) are what stop it from repeating — but a bare prompt
        # with no reason reads as suspicious; these explain it.
        "NSDesktopFolderUsageDescription": (
            "FusedRender previews files you open from your Desktop."
        ),
        "NSDocumentsFolderUsageDescription": (
            "FusedRender previews files you open from your Documents folder."
        ),
        "NSDownloadsFolderUsageDescription": (
            "FusedRender previews files you open from your Downloads folder."
        ),
        "NSRemovableVolumesUsageDescription": (
            "FusedRender previews files you open from removable volumes."
        ),
        "NSNetworkVolumesUsageDescription": (
            "FusedRender previews files you open from network volumes."
        ),
    },
}

setup(
    app=APP,
    name="FusedRender",
    version=VERSION,
    options={"py2app": OPTIONS},
    # py2app is already installed into the build venv directly (see
    # build_dmg.sh) - not declared as setup_requires: modern setuptools
    # dropped the old easy_install-based fetch-at-setup-time mechanism
    # entirely ("install_requires is no longer supported" if you try).
)
