"""py2app build spec for FusedRender.app (SPEC D33-D35).

Invoked by build_dmg.sh as:
    python scripts/setup_py2app.py py2app --dist-dir <dir>

Not a normal package build — `python_requires`/deps etc. are irrelevant here;
this only describes how py2app should assemble the .app bundle. The actual
fused-render + [bundled,app] install happens into the build venv beforehand
(see build_dmg.sh); py2app then copies what's importable from that venv.

`packages` (below) forces WHOLE-DIRECTORY copies instead of py2app's default
"trace imports statically, freeze into a zip" behavior. Two independent
reasons every one of these needs it:
  1. Binary/data-bearing packages (numpy, pandas, pyarrow, duckdb, pillow,
     ...) ship .so/.dylib files and non-Python data that a zipped archive
     can't hold anyway.
  2. fused-render's own executor model: `runPython` loads arbitrary user .py
     files via importlib in a CHILD PROCESS (_child.py), not via a static
     `import` anywhere in fused_render's own source. py2app's modulegraph
     only sees imports it can trace from app_entry.py's call graph, so it
     is structurally blind to whatever a user's script imports at runtime
     (pandas, pyarrow, PIL, ...). Every package promised by the `[bundled]`
     extra (SPEC DM-2) must therefore be forced in explicitly — there is no
     static import for modulegraph to find in the first place.
"""
import os
import re
import sys

from fused_render._branch import branch_ref, branch_suffix

# `setuptools` is imported lazily inside the build guard below: this module must
# stay importable by tests/test_bundle_contents.py, which runs in the plain test
# venv where setuptools is not a dependency.

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(SCRIPT_DIR)

# Single source of truth is fused_render/__init__.py's __version__ (pyproject
# derives it dynamically via [tool.hatch.version] — no literal version line).
with open(os.path.join(REPO_ROOT, "fused_render", "__init__.py")) as f:
    _init = f.read()
VERSION = re.search(r'(?m)^__version__\s*=\s*"([^"]+)"', _init).group(1)

# Generated by build_dmg.sh before invoking py2app (see its icon-generation
# step) — not committed, lives under build/.
ICONFILE = os.environ.get("FUSED_RENDER_ICNS")
# Only fatal when actually building. Guarded so this module stays IMPORTABLE:
# tests/test_bundle_contents.py reads BUNDLED_EXCLUDED and OPTIONS from it to
# reconcile the bundle against `[bundled]`, and an unconditional sys.exit here
# would make that impossible — which is how the list drifted unnoticed before.
_BUILDING = "py2app" in sys.argv
if _BUILDING and (not ICONFILE or not os.path.isfile(ICONFILE)):
    sys.exit(f"FUSED_RENDER_ICNS must point at an existing .icns file (got: {ICONFILE!r})")

APP = [os.path.join(SCRIPT_DIR, "app_entry.py")]

# ---------------------------------------------------------------------------
# What the `[bundled]` extra contributes to the bundle — DERIVED, not listed
# ---------------------------------------------------------------------------
#
# py2app needs explicit package names (modulegraph cannot see what a template
# imports at runtime — see the module docstring's second reason). It does not
# need a HUMAN to supply them. Three separate hand-maintained lists in this
# project have silently diverged from what they were supposed to mirror
# (`engine.DEFAULT_REQUIREMENTS` vs `[bundled]`; template PEP 723 headers that
# were never read; and this `packages` list vs `[bundled]`, which shipped a DMG
# where opening a .pptx said "pip install python-pptx" — advice a DMG user
# cannot follow). D177 is the standing rule that came out of that: derive, or
# make divergence a test failure. This derives.
#
# `importlib.metadata` over the BUILD VENV: read the distributions `[bundled]`
# actually resolved to, walk their runtime requirements, and force the resulting
# top-level import names. Transitive deps (lxml, numcodecs, cachetools, affine,
# cligj...) come along for free, which is the whole point — they were previously
# either hand-listed or, worse, arriving incidentally.

# Distributions from `[bundled]` that this bundle deliberately does NOT ship.
# Currently none, and D276 is the reason it STAYED none while 541.9 MB came out of
# the bundle: the size problem was solved by shrinking `[bundled]` itself, so all
# three platform builds got smaller together. Excluding here would have shrunk
# only macOS, leaving Linux and Windows carrying packages the extra still
# promises — which is D176's defect exactly, in the other direction. The rule is
# unchanged: this dict is for a distribution the EXTRA still needs and the macOS
# BUNDLE cannot carry, not for one the product no longer wants.
#
# The mechanism stays even while the dict is empty, and that is the point. It
# makes the bundle's invariant enforceable: every `[bundled]` distribution
# either ships, or is named here with its MEASURED cost — never just quietly
# absent, which is the state that shipped a DMG telling users to run a pip
# command they cannot run. An entry maps a distribution name (as spelled in
# `[bundled]`) to a short string stating that cost and the reason;
# `tests/test_bundle_contents.py::test_every_exclusion_is_declared_and_reasoned`
# rejects entries that name a non-`[bundled]` distribution or omit a size, and
# `test_the_bundle_ships_everything_it_does_not_explicitly_exclude` fails for
# anything missing that is not listed here. When a genuinely large dependency
# does need holding back, both the machinery and its tests are already here.
#
# Excluding a distribution has a real consequence to weigh: a script venv cannot
# see the app's site-packages, so every template that imports it must declare its
# COMPLETE third-party closure in its folder's `pyproject.toml` (SPEC PY-16), and
# everything else in that closure gets re-downloaded per venv.
BUNDLED_EXCLUDED = {}

# Top-level names that must never be forced via `packages`, whatever the
# metadata says. PEP 420 namespace packages (no `__init__.py`) break py2app's
# package-bootstrap lookup — the same limitation already documented for
# mpl_toolkits and PyObjCTools below. `google` (google-auth) is handled by
# naming its real SUBPACKAGES in `packages` instead; py2app supports dotted
# entries (build_app.py: `included_subpkg = [pkg for pkg in self.packages if
# "." in pkg]`). `__pycache__` is an artifact of resolving names from RECORD.
NEVER_FORCE_AS_PACKAGE = {"mpl_toolkits", "PyObjCTools", "google", "__pycache__"}

# Top-level names the derivation must route to `includes` even though they look
# like packages on disk, or must not duplicate. `_duckdb` is the bare C extension
# the comment in `packages` below explains at length; it is already in the
# explicit `includes` list, and the derivation must not also force it.
ALREADY_IN_INCLUDES = {"_duckdb", "_cffi_backend"}

# Packages copied into the bundle by build_dmg.sh AFTER py2app runs, instead of
# being forced through `packages`.
#
# `google` (google-auth) is here because py2app cannot carry it either way:
#   * as `"google"` it is a PEP 420 namespace package with no `__init__.py`, and
#     py2app's package bootstrap cannot resolve those — the limitation already
#     documented for mpl_toolkits and PyObjCTools below;
#   * as `"google.auth"`/`"google.oauth2"` the build dies outright.
#     `collect_packagedirs()` (build_app.py:1210) maps `get_bootstrap()` over
#     EVERY entry of `self.packages`, dotted included, and that calls
#     `modulegraph.util.imp_find_module`, which splits the name and calls
#     `imp.find_module("google")` — ImportError, before py2app's own
#     dotted-aware `included_subpkg` path is ever reached. Tried; it fails the
#     build. `tests/test_bundle_contents.py` now rejects dotted entries so this
#     cannot be reintroduced by a unit test that passes while the build breaks.
#
# Staging it explicitly is the same pattern as rclone and uv (steps 4d/4d-bis):
# a plain copy, no modulegraph involvement, and the namespace parent comes along
# by construction. `[bundled]`'s own comment is the authority for shipping it at
# all — the cloud-auth chain was folded into the bundled app precisely because
# "DMG users cannot pip install". Its dependencies (pyasn1, pyasn1-modules,
# cryptography) are ordinary packages and stay in the derived list.
STAGED_PACKAGES = ["google"]


def _norm_dist(name):
    return name.lower().replace("_", "-")


def _req_name(requirement):
    name = requirement.split("[")[0]
    for sep in ("<", ">", "=", "!", "~", " ", "(", ";"):
        name = name.split(sep)[0]
    return _norm_dist(name.strip())


def _bundled_distributions():
    """The distributions the app's own interpreter must provide, minus exclusions.

    `[bundled]` AND `[project] dependencies` — both, because that pair is exactly
    what SPEC PY-17 promises a header-less script (pyarrow and duckdb are *core*
    deps, not part of the extra, and the tabular readers are unusable without
    them). Reading only the extra is how an earlier version of this change
    silently dropped them from the bundle.
    """
    # tomllib is 3.11+ stdlib; `tomli` is the same parser and is a dependency on
    # 3.10 (see pyproject). This module is imported by
    # tests/test_bundle_contents.py, which runs on the whole 3.10-3.13 matrix, so
    # it cannot assume the newer name.
    try:
        import tomllib
    except ImportError:
        import tomli as tomllib

    with open(os.path.join(REPO_ROOT, "pyproject.toml"), "rb") as fh:
        pyproject = tomllib.load(fh)
    declared = list(pyproject["project"]["optional-dependencies"]["bundled"])
    declared += list(pyproject["project"]["dependencies"])
    excluded = {_norm_dist(n) for n in BUNDLED_EXCLUDED}
    return [_req_name(d) for d in declared if _req_name(d) not in excluded]


def _runtime_requires(dist):
    """Runtime deps of `dist`, skipping extras and unsatisfied markers."""
    out = []
    for raw in dist.requires or []:
        spec = raw
        if ";" in raw:
            head, marker = raw.split(";", 1)
            if "extra" in marker:
                continue  # optional extra: not installed, not needed
            try:
                from packaging.markers import Marker

                if not Marker(marker.strip()).evaluate():
                    continue
            except Exception:
                pass
            spec = head
        name = _req_name(spec)
        if name:
            out.append(name)
    return out


def bundled_force_lists():
    """(packages, includes) contributed by `[bundled]`, derived from the venv.

    Split by what each top-level name actually IS on disk, because py2app
    handles the two differently and getting it wrong is silent: a bare module or
    C extension forced via `packages` gets copied as `lib/python3.12/<name>.py`,
    which shadows the real thing (see the `_duckdb` comment below).
    """
    import importlib.metadata as importlib_metadata
    import sysconfig

    # BOTH site directories, because the two schemes are not always one path:
    # pure-Python distributions land in `purelib`, extension ones (numpy, pandas,
    # pyarrow, duckdb) in `platlib`. They coincide in a venv, so probing
    # only `purelib` works here and silently misfiles every native package on any
    # interpreter where they differ — sending it to `includes`, i.e. the bare-.py
    # shadowing failure the `_duckdb` comment below describes.
    _paths = sysconfig.get_paths()
    site_dirs = []
    for scheme in ("purelib", "platlib"):
        d = _paths.get(scheme)
        if d and d not in site_dirs:
            site_dirs.append(d)
    installed = {}
    for dist in importlib_metadata.distributions():
        name = dist.metadata["Name"] if dist.metadata else None
        if name:
            installed[_norm_dist(name)] = dist

    # Transitive closure over the non-excluded [bundled] distributions.
    excluded = {_norm_dist(n) for n in BUNDLED_EXCLUDED}
    seen, stack = set(), list(_bundled_distributions())
    while stack:
        name = stack.pop()
        if name in seen or name in excluded:
            continue
        seen.add(name)
        dist = installed.get(name)
        if dist is None:
            # Not installed in the build venv: a marker-gated or extra-only dep.
            # Nothing to copy, so nothing to force.
            continue
        stack.extend(_runtime_requires(dist))

    # distribution -> top-level import names, from metadata rather than guesswork
    # (python-pptx -> pptx, pillow -> PIL, google-auth -> google).
    top_level = {}
    for import_name, dist_names in importlib_metadata.packages_distributions().items():
        for dist_name in dist_names:
            top_level.setdefault(_norm_dist(dist_name), set()).add(import_name)

    packages, includes = set(), set()
    for name in seen:
        for import_name in top_level.get(name, ()):
            if import_name in NEVER_FORCE_AS_PACKAGE or import_name in ALREADY_IN_INCLUDES:
                continue
            path = next(
                (p for p in (os.path.join(s, import_name) for s in site_dirs)
                 if os.path.isdir(p)),
                None,
            )
            if path is not None:
                if os.path.exists(os.path.join(path, "__init__.py")):
                    packages.add(import_name)
                # else: a namespace package we did not whitelist — skip it rather
                # than force it and break py2app's bootstrap.
            else:
                # Bare module or C extension: `includes`, never `packages`.
                includes.add(import_name)
    # STAGED_PACKAGES are deliberately NOT added here: py2app cannot carry them
    # (see the constant), so build_dmg.sh copies them in afterwards.
    packages.difference_update(STAGED_PACKAGES)
    return sorted(packages), sorted(includes)


BUNDLED_PACKAGES, BUNDLED_INCLUDES = bundled_force_lists()


# Extensions the built-in template registry (server.py TEMPLATES) previews,
# kept in sync by hand (see ARCHITECTURE.md §7), plus geo/sci extras with no
# built-in key — users can bind those via the runtime template registry, and
# extra Finder associations are harmless at Alternate rank.
_PREVIEWABLE_EXTENSIONS = [
    "html", "htm", "csv", "tsv", "json", "geojson", "md", "txt", "log",
    "yaml", "yml", "toml", "py", "js", "ts", "sh", "css",
    "png", "jpg", "jpeg", "gif", "webp", "svg", "xlsx", "pdf",
    "mp4", "mov", "m4v", "webm", "mp3", "wav", "m4a", "ogg", "flac",
    "tif", "tiff", "geotiff",  # GeoTIFF rasters (server.py "geotiff" template)
    "nc", "nc4", "cdf",  # NetCDF (server.py "netcdf" template)
    "h5", "hdf5", "he5", "hdf",  # HDF (server.py "map" template)
    # geo/sci formats with no built-in template key — bindable via the
    # runtime template registry:
    "gpkg", "shp", "fgb", "kml", "kmz", "gpx", "las", "laz",
    "pmtiles", "mbtiles", "zarr", "grib2", "jp2",
]

DOCUMENT_TYPES = [
    {
        # `.bookmark` is our own format (SB-9, D99): declare the UTI below and
        # claim Owner rank so a Finder double-click always opens FusedRender.
        "CFBundleTypeName": "FusedRender bookmark",
        "CFBundleTypeRole": "Viewer",
        "LSHandlerRank": "Owner",
        "CFBundleTypeExtensions": ["bookmark"],
        "LSItemContentTypes": ["io.fused.render.bookmark"],
    },
    {
        "CFBundleTypeName": "Apache Parquet data",
        "CFBundleTypeRole": "Viewer",
        "LSHandlerRank": "Default",  # no other app owns .parquet
        "CFBundleTypeExtensions": ["parquet"],
    },
    {
        "CFBundleTypeName": "FusedRender previewable file",
        "CFBundleTypeRole": "Viewer",
        "LSHandlerRank": "Alternate",  # never steals the user's default app
        "CFBundleTypeExtensions": _PREVIEWABLE_EXTENSIONS,
    },
]

# --- the standard library itself ---------------------------------------------
#
# **py2app ships the stdlib THIS APP IMPORTS, not the standard library**, and
# that is a promise the app makes to code it never traced.
#
# modulegraph freezes what it can reach from `app_entry.py` into
# `Contents/Resources/lib/python312.zip`. Nothing in fused_render imports
# `filecmp`, so `filecmp` was not in that zip — and the bundled interpreter is
# the BASE INTERPRETER of every environment the app builds (PY-18: `uv sync
# --python Contents/MacOS/python`), so a venv inherits that hole. On a DMG,
# loading a Qwen model died with:
#
#     transformers/dynamic_module_utils.py:17  import filecmp
#     ModuleNotFoundError: No module named 'filecmp'
#
# which transformers' lazy-import machinery re-raised as `Could not import
# module 'AutoTokenizer'` — a message about the model, three layers away from a
# missing stdlib module. mlx-lm, transformers and tokenizers were all installed
# correctly; the install was never interrupted.
#
# The subset is only ever right by luck: it is the intersection of the stdlib
# with what THIS app happens to import, and every dependency any user installs
# is entitled to the rest of it. So the whole importable stdlib is forced in.
#
# Split the way the rest of this file splits: a package (`email`, `xml`,
# `encodings`) goes to `packages` for a whole-directory copy, because
# modulegraph would otherwise carry only the submodules it traced; a plain
# module or C extension goes to `includes`.
#
# Builtins are skipped — they are compiled into the interpreter, so there is no
# file to copy — and anything `find_spec` cannot resolve on the build host is
# skipped too, which is what keeps the Windows-only names (`msvcrt`, `winreg`,
# `winsound`) out of a macOS build.

#: Stdlib names the bundle deliberately does NOT carry, each with the reason it
#: is safe to omit. Anything absent from the bundle must be here rather than
#: merely missing — that is the rule `test_the_bundle_ships_everything_it_does
#: _not_explicitly_exclude` already applies to distributions, applied to the
#: stdlib, and it is what makes the next `filecmp` a failed build rather than a
#: user's bug report.
STDLIB_EXCLUDED = {
    "tkinter": "the GUI is rumps/pyobjc, and build_dmg.sh prunes Tcl/Tk",
    "idlelib": "the bundled IDE; nothing in the app runs it",
    "turtle": "imports tkinter at module level, so it cannot work without it",
    "turtledemo": "demo suite for turtle",
    # `test` (CPython's own suite) needs no entry: it is not in
    # `sys.stdlib_module_names`, so the derivation never sees it. build_dmg.sh
    # prunes the framework's copy separately.
    "ensurepip": "no pip in the bundle by design (SPEC §19 DP-3)",
    "lib2to3": "2-to-3 dev tooling, removed upstream in 3.13",
    "antigravity": "opens a web browser at import time",
    "this": "an easter egg; the Zen of Python is not a dependency",
}


def _stdlib_split():
    """`(packages, includes)` covering the importable stdlib on this host."""
    import importlib.util

    packages, includes = [], []
    for name in sorted(sys.stdlib_module_names):
        if name in STDLIB_EXCLUDED or name.startswith("__"):
            continue
        if name in sys.builtin_module_names:
            continue  # compiled in; there is no file to carry
        try:
            spec = importlib.util.find_spec(name)
        except (ImportError, ValueError):
            continue  # unresolvable here (a platform module for another OS)
        if spec is None:
            continue
        if spec.submodule_search_locations is not None:
            packages.append(name)
        else:
            includes.append(name)
    return packages, includes


STDLIB_PACKAGES, STDLIB_INCLUDES = _stdlib_split()


OPTIONS = {
    "argv_emulation": False,  # rumps/app.py owns AppKit file-open handling directly (application:openFiles:)
    "iconfile": ICONFILE,
    "packages": [
        "fused_render",
        # `[bundled]` and its transitive deps are appended below from
        # BUNDLED_PACKAGES (derived above) — deliberately not hand-listed.
        # Everything that follows is NOT part of [bundled] and stays explicit:
        # the web/app stack, the fused CLI's data-bearing deps, and the AppKit
        # shell.
        # web server stack: forced full-copy too, since uvicorn/pydantic-core
        # do dynamic/compiled imports modulegraph can't always follow.
        "fastapi", "starlette", "uvicorn", "h11", "click", "anyio",
        "pydantic", "pydantic_core", "typing_extensions", "typing_inspection",
        "annotated_types", "annotated_doc", "packaging",
        # menu-bar app shell. PyObjCTools deliberately excluded: same
        # namespace-package (no __init__.py) limitation as mpl_toolkits
        # above. rumps's own static `import` of what it needs from
        # PyObjCTools (e.g. AppHelper) is still picked up normally by
        # modulegraph's regular import tracing - only forcing the whole
        # package via `packages` breaks on its bootstrap lookup.
        "rumps", "objc", "AppKit", "Foundation", "Cocoa", "CoreFoundation",
        # Pinned view (SPEC §25, D97): WKWebView for the status-item popover.
        "WebKit",
        # The execution engine and deploy CLI (D69, D79, SPEC §19 DP-3), run
        # in-bundle via fused_render/_fused_cli.py. `fused` ITSELF is no longer
        # named here: it is a `[bundled]` requirement, so BUNDLED_PACKAGES below
        # derives it (forced whole, which is what it needs — pluggy entry-point
        # plugins + pervasive in-function imports + non-.py package data) and
        # test_bundle_contents.py's reconciliation fails if the bundle would
        # ever stop carrying it. A hand entry could not be checked that way,
        # which for the engine meant it could vanish with the suite still green.
        #
        # These deps stay explicit: they carry data dirs or dynamic loading that
        # a traced-module copy would drop — botocore's JSON service models
        # (boto3), anthropic's tokenizer data, keyring's entry-point backends,
        # cryptography's cffi bindings, pluggy's registry. The derivation now
        # reaches most of them through `fused`'s requirements too, and the
        # duplication is harmless (py2app de-dupes); they are kept named because
        # the REASON they must be whole-copied is not derivable from metadata.
        # The rest of fused's dep tree is pure-python with ordinary imports —
        # modulegraph traces it. The gate for anything missed here is
        # build_dmg.sh §4c's bundled-CLI smoke test (real verbs through the
        # shim). `ty` is deliberately NOT shipped (a Rust binary console script
        # py2app can't carry); fused's verify scanner detects its absence and
        # skips with a warning finding.
        "boto3", "botocore", "s3transfer", "jmespath",
        "cryptography", "keyring",
        "anthropic", "mcp", "httpx", "httpcore",
        "pluggy", "tomlkit", "jwt", "yaml", "loguru",
        "aiohttp", "yarl", "multidict", "frozenlist",
        "fsspec", "tabulate", "tqdm", "rtoml",
    ] + BUNDLED_PACKAGES + STDLIB_PACKAGES,
    # Single modules (incl. bare C extensions) that modulegraph can't be
    # trusted to find on its own — same runtime-import blindness as
    # `packages` above, but `includes` handles non-package modules correctly
    # (extension -> lib-dynload/*.so, never a bogus .py copy).
    # _cffi_backend: cryptography's cffi backend, the same bare-top-level-
    # C-extension shape as _duckdb.
    "includes": ["_duckdb", "_cffi_backend"] + BUNDLED_INCLUDES + STDLIB_INCLUDES,
    # Skip py2app's "missing conditional import" report. Not cosmetic: that
    # report `__import__`s every module name modulegraph could not resolve, in
    # order to classify it, and catches only `Exception` — so a name whose import
    # raises SystemExit (a package's `__main__`, a module that calls sys.exit at
    # import time) terminates the build with NO traceback and no message, right
    # after py2app's own codesign line makes it look like it succeeded. That is
    # what a CI run did. The set of "missing" names depends on what is installed,
    # so it differs per machine, which is why a local build passed. We never read
    # this report; the unconditional one (which cannot be disabled, but does skip
    # `.__main__` names — `build_app.py`'s loop `continue`s on that suffix, which
    # is why this flag is enough for the `__main__` case) still prints anything
    # actionable. NOT closed by this flag: the unconditional report probes every
    # remaining missing name the same way and also catches only `Exception`, so a
    # module that is not a `__main__` and raises SystemExit at import can still
    # end the build after the codesign line. Nothing installed does today; if one
    # ever does, name it in `expected_missing_imports` (the only list
    # `may_log_missing` consults) rather than widening this flag.
    "no_report_missing_conditional_import": True,
    "plist": {
        "CFBundleIdentifier": "io.fused.render" + (f".{branch_ref()}" if branch_ref() else ""),
        "CFBundleName": f"FusedRender{branch_suffix()}",
        "CFBundleDisplayName": f"FusedRender{branch_suffix()}",
        "CFBundleShortVersionString": VERSION,
        "CFBundleVersion": VERSION,
        "LSMinimumSystemVersion": "11.0",
        "NSHighResolutionCapable": True,
        # No LSUIElement (D34): regular app, Dock icon + menu bar item both.
        # Finder "Open with FusedRender" (SPEC DM-8):
        "CFBundleDocumentTypes": DOCUMENT_TYPES,
        # fused-render:// deep links (SPEC §26, D110): delivered to
        # application:openURLs: in app.py. Scheme deliberately NOT
        # branch-suffixed (same rationale as the bookmark UTI below): every
        # build speaks the same links, LaunchServices picks one handler.
        "CFBundleURLTypes": [
            {
                "CFBundleURLName": "io.fused.render.deeplink",
                "CFBundleURLSchemes": ["fused-render"],
            }
        ],
        # No other app defines `.bookmark`, so export the UTI ourselves —
        # without this, LaunchServices treats the extension as dynamic data
        # and the Owner rank above binds unreliably. Identifier deliberately
        # NOT branch-suffixed: every FusedRender build describes the same
        # file format, even though only one can be the Finder default.
        "UTExportedTypeDeclarations": [
            {
                "UTTypeIdentifier": "io.fused.render.bookmark",
                "UTTypeDescription": "FusedRender bookmark",
                "UTTypeConformsTo": ["public.json"],
                "UTTypeTagSpecification": {"public.filename-extension": ["bookmark"]},
            }
        ],
        # macOS shows these strings in the TCC permission prompt when the app
        # first reads a file under a protected folder (the app browses the
        # whole filesystem by design, D2). Purpose strings don't change WHEN
        # the prompt appears — the D72 in-process-reader split + Developer ID
        # signing (D73) are what stop it from repeating — but a bare prompt
        # with no reason reads as suspicious; these explain it.
        "NSDesktopFolderUsageDescription": (
            "FusedRender previews files you open from your Desktop."
        ),
        "NSDocumentsFolderUsageDescription": (
            "FusedRender previews files you open from your Documents folder."
        ),
        "NSDownloadsFolderUsageDescription": (
            "FusedRender previews files you open from your Downloads folder."
        ),
        "NSRemovableVolumesUsageDescription": (
            "FusedRender previews files you open from removable volumes."
        ),
        "NSNetworkVolumesUsageDescription": (
            "FusedRender previews files you open from network volumes."
        ),
    },
}

if _BUILDING:
    from setuptools import setup

    setup(
        app=APP,
        name=f"FusedRender{branch_suffix()}",
        version=VERSION,
        options={"py2app": OPTIONS},
        # py2app is already installed into the build venv directly (see
        # build_dmg.sh) - not declared as setup_requires: modern setuptools
        # dropped the old easy_install-based fetch-at-setup-time mechanism
        # entirely ("install_requires is no longer supported" if you try).
    )
